# ===============================
# APP
# ===============================
spring.application.name=deposito
server.port=8080

# ===============================
# DATABASE (LOCAL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/deposito
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ===============================
# MAIL (DEV)
# ===============================
spring.mail.host=in-v3.mailjet.com
spring.mail.port=2525

spring.mail.username=6a20472cbc8a17dd29022c4dfa5fe66f
spring.mail.password=25bf164bcf9f40d448534e80622243cb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# JWT
# ===============================
security.jwt.secret-key=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIEpXVC4uLg==
security.jwt.expiration-time=900000
security.jwt.refresh-expiration=604800000

# ===============================
# ADMIN (DEV)
# ===============================
app.admin.email=kevinolarte.ko@gmail.com
app.admin.password=1234
app.admin.name=kevin

# ===============================
# CORS (DEV)
# ===============================
app.cors.allowed-origins=*
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
app.cors.exposed-headers=Authorization,Content-Disposition
app.cors.allow-credentials=false
app.cors.max-age=3600